Repository quantumjot/btrack, pull requests merged in 2022-03, with the labels that each got.

#79 Add deploy action
  .github/workflows/deploy.yml
  docs/dev_guide/index.rst
Labels: feature, documentation

#95 Enable black string formatting
  .gitignore
  btrack/_localization.py
  btrack/btypes.py
  btrack/core.py
  btrack/dataio.py
  btrack/libwrapper.py
  btrack/models.py
  btrack/optimise/hypothesis.py
  btrack/optimise/optimiser.py
  btrack/utils.py
  docs/conf.py
  pyproject.toml
  setup.py
  tests/_utils.py
  tests/test_io.py
  tests/test_tracker.py
Labels: optimization

#101 Bump `black` to fix
  .pre-commit-config.yaml
Labels: bug
