Repository quantumjot/btrack, pull requests merged in 2022-02, with the labels that each got.

#53 Separate models
  CHANGELOG.rst
  btrack/btypes.py
  btrack/core.py
  btrack/models.py
  btrack/optimise/hypothesis.py
  btrack/utils.py
  tests/test_models.py
Labels: feature, documentation

#59 update segmentation tests to use poisson disc sampling
  tests/test_utils.py
Labels: bug

#68 Make `isort` compatible with `black` by changing line length
  .pre-commit-config.yaml
  btrack/_localization.py
  btrack/btypes.py
  btrack/core.py
  btrack/dataio.py
  btrack/libwrapper.py
  btrack/models.py
  btrack/optimise/hypothesis.py
  pyproject.toml
Labels: bug

#77 Fix export delegator
  btrack/dataio.py
  tests/_utils.py
  tests/test_io.py
  tests/test_tracker.py
Labels: bug

#76 Use `requirements.txt` in `environment.yml` to avoid repetition
  README.md
  environment.yml
  requirements.txt
Labels: documentation

#73 add saving and loading track data documentation
  docs/user_guide/index.rst
  docs/user_guide/saving_tracks.rst
Labels: documentation

#81 Fix optimizer configuration
  btrack/models.py
  btrack/optimise/hypothesis.py
  examples/napari_btrack.ipynb
  tests/_test_data/test_graph.json
  tests/_utils.py
  tests/test_tracker.py
Labels: bug
