Repository quantumjot/btrack, pull requests merged in 2023-06, with the labels that each got.

#329 Add updated `tox` configuration
  pyproject.toml
Labels: CI

#334 Add legacy h5 support and tree inspection
  btrack/io/hdf.py
  tests/test_io.py
Labels: bug, feature

#336 Fix formatting for developer guide
  docs/dev_guide/index.rst
Labels: documentation
