Repository quantumjot/btrack, pull requests merged in 2023-05, with the labels that each got.

#320 Fix plugin name in example script
  btrack/napari/examples/show_btrack_widget.py
Labels: bug

#326 Minimise tox dependencies
  pyproject.toml
Labels: CI

#325 Drop python 3.8 support & napari backends
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  btrack/btypes.py
  btrack/config.py
  btrack/core.py
  btrack/datasets.py
  btrack/io/_localization.py
  btrack/io/hdf.py
  btrack/io/importers.py
  btrack/io/utils.py
  btrack/models.py
  btrack/napari/reader.py
  btrack/optimise/optimiser.py
  btrack/utils.py
  pyproject.toml
  tests/_utils.py
  tests/conftest.py
  tests/test_config.py
Labels: napari-plugin, CI
