Repository quantumjot/btrack, pull requests merged in 2023-04, with the labels that each got.

#294 Include binaries and upload to testpypi
  .github/workflows/deploy.yml
  MANIFEST.in
  pyproject.toml
Labels: bug, CI

#298 Fix H5 docstrings
  btrack/io/hdf.py
Labels: documentation

#300 Build wheels on earlier OS versions & verify binaries are included
  .github/workflows/deploy.yml
  .github/workflows/linting.yml
  .github/workflows/test.yml
  README.md
  docs/dev_guide/index.rst
  docs/user_guide/installation.rst
Labels: bug, CI

#305 Scale image in layer
  btrack/napari/main.py
  tests/napari/test_dock_widget.py
Labels: bug
